services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"


  app:
    build: .
    image: resource-management-app:1.0
    container_name: resource-management-app
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      DB-name: ${POSTGRES_DB}
      DB-username: postgres
      DB-password: ${POSTGRES_PASSWORD}


