server.port=8081
server.error.include-exception=true
server.error.include-message=always

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/${DB-name}
spring.datasource.username=${DB-username}
spring.datasource.password=${DB-password}
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.app.numberOfCategories=5
spring.app.numberOfProducts=10
spring.app.pageSize=10
